### ISSUE TITLE
Custom compotent tasmota unavailable

### ISSUE THREAD

**Issue by Igor-kr** [hhaim/hass#19] opened 2020-08-02 05:46 UTC
Hi. I am trying to install your custom component, but it doesn't seem to work for me. I copied the folder tasmota to the folder custom_components and added this -
  - platform: tasmota
    name: hot_water_total
    stopic: tasmota_4B0C0B
    id: 2
    max_valid_diff: 2000
    unit_of_measurement: 'l'
    icon: mdi: water-pump
    expire_after: 300
    value_template: "{{(505360 + (value * 10)) | int}}"

to the my configuration.yaml file. After restart, in states **sensor.hot_water_tota**l - shows **unavailable**

On the other hand, this component works fine.
  - platform: mqtt
    name: "cold_water"
    state_topic: "tele / tasmota_4B0C0B / SENSOR"
    value_template: "{{value_json.COUNTER.C1}}"
    json_attributes_topic: "tele / tasmota_4B0C0B / SENSOR"
    json_attributes_template: "{{value_json.COUNTER | tojson}}"

I started the mgt_dump service and this is what we have:

tele / tasmota_4B0C0B / SENSOR, {"Time": "2020-08-02T11: 05: 20", "COUNTER": {"C1": 9, "C2": 311, "C3": 53}, "ANALOG" : {"A0": 4}, "DS18B20": {"Id": "021618547BEE", "Temperature": 33.3}, "TempUnit": "C"}
tele / tasmota_4B0C0B / STATE, {"Time": "2020-08-02T11: 06: 20", "Uptime": "0T07: 23: 12", "UptimeSec": 26592, "Heap": 26, "SleepMode" : "Dynamic", "Sleep": 250, "LoadAvg": 37, "MqttCount": 1, "Wifi": {"AP": 1, "SSId": "Igor", "BSSId": "D0: 54 : 2D: 01: 24: 70 "," Channel ": 1," RSSI ": 62," Signal ": - 69," LinkCount ": 1," Downtime ":" 0T00: 00: 03 "}}
tele / tasmota_4B0C0B / SENSOR, {"Time": "2020-08-02T11: 06: 20", "COUNTER": {"C1": 9, "C2": 311, "C3": 53}, "ANALOG" : {"A0": 4}, "DS18B20": {"Id": "021618547BEE", "Temperature": 33.3}, "TempUnit": "C"}
tele / tasmota_4B0C0B / STATE, {"Time": "2020-08-02T11: 07: 20", "Uptime": "0T07: 24: 12", "UptimeSec": 26652, "Heap": 24, "SleepMode" : "Dynamic", "Sleep": 250, "LoadAvg": 26, "MqttCount": 1, "Wifi": {"AP": 1, "SSId": "Igor", "BSSId": "D0: 54 : 2D: 01: 24: 70 "," Channel ": 1," RSSI ": 70," Signal ": - 65," LinkCount ": 1," Downtime ":" 0T00: 00: 03 "}}
tele / tasmota_4B0C0B / SENSOR, {"Time": "2020-08-02T11: 07: 20", "COUNTER": {"C1": 9, "C2": 311, "C3": 53}, "ANALOG" : {"A0": 4}, "DS18B20": {"Id": "021618547BEE", "Temperature": 33.3}, "TempUnit": "C"}
MQQT works!

Home Assistant version 0.113.2

What am I doing wrong?

**Comment by hhaim** [comment] 2020-08-02 06:23
You should put the Id:1 for C1

**Comment by hhaim** [comment] 2020-08-02 06:28
I would look into hass logs too

**Comment by Igor-kr** [comment] 2020-08-02 06:33
If i need C2  Id:2 it correct?

Log 
2020-08-02 12:29:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for currentcost which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-02 12:29:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tasmota which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-02 12:30:01 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2020-08-02 12:30:01 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-02 12:30:01 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 5 seconds
2020-08-02 12:30:07 WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform met is taking over 10 seconds.
2020-08-02 12:30:07 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform systemmonitor is taking over 10 seconds.
2020-08-02 12:30:07 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform integration is taking over 10 seconds.
2020-08-02 12:30:12 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-02 12:30:12 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 10 seconds
2020-08-02 12:30:25 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-02 12:30:25 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 20 seconds
2020-08-02 12:30:48 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-02 12:30:48 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 40 seconds
2020-08-02 12:31:01 WARNING (MainThread) [frontend.js.latest.202007160] Icon mdi:square-inc-cash was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 0.115.
2020-08-02 12:31:01 WARNING (MainThread) [frontend.js.latest.202007160] Icon mdi:square-inc-cash was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 0.115.

**Comment by Igor-kr** [comment] 2020-08-02 06:37
With ID1 also does not work

**Comment by hhaim** [comment] 2020-08-02 06:40
Could you filter the hass log for tasmota only messages

**Comment by Igor-kr** [comment] 2020-08-02 07:19
Just this

2020-08-02 12:29:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tasmota which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
in file home-assistant.log

**Comment by hhaim** [comment] 2020-08-02 13:16
@Igor-kr 
I've tested it with ```Home Assistant 0.113.3``` it works fine 

The id should be the value of cx for C1 it should be 1 

```Id: 1```

I would add a log here 
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L145
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L140

To verify mqtt payloads 

Something like this 

_LOGGER.error("payload %s", payload)

**Comment by Igor-kr** [comment] 2020-08-03 03:44
Hi, I added these commands, and this is what came out in the log.

2020-08-03 09:36:20 ERROR (MainThread) [custom_components.tasmota.sensor] payload {"Time":"2020-08-03T09:36:19","Uptime":"0T05:53:11","UptimeSec":21191,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":35,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:03"}}
2020-08-03 09:36:20 ERROR (MainThread) [custom_components.tasmota.sensor] payload {"Time":"2020-08-03T09:36:19","COUNTER":{"C1":0,"C2":338,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":33.8},"TempUnit":"C"}

I do not understand, if I need readings from C2, should I set ID:2? Or does the component only work with C1?

**Comment by hhaim** [comment] 2020-08-03 04:10
Your payloads looks good. The component should work. For C2 you should set id:2 

Could you go to developer page and look into the sensor internal Info

**Comment by Igor-kr** [comment] 2020-08-03 04:55
Thank you for your help.
It still unavailable
![IMG_3028](https://user-images.githubusercontent.com/68376689/89146559-ee0de780-d575-11ea-8cc7-680c06ba7da3.jpg)

  - platform: tasmota
    name: hot_water_total
    stopic: tasmota_4B0C0B
    id: 1
    max_valid_diff: 2000
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (505360 + (value*10))|int }}"

With **value_template** everything ok??

**Comment by hhaim** [comment] 2020-08-03 05:00
Try to add more logs into the code. I don’t understand why. 
I would try to set the expire after to 0

**Comment by hhaim** [comment] 2020-08-03 05:56
try to remove this lines
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L193
![image](https://user-images.githubusercontent.com/13034429/89150421-2fe36180-d567-11ea-8801-db4901848cd8.png)

I think your counters does not change for very long time so it stuck in the first state

**Comment by Igor-kr** [comment] 2020-08-03 06:29
Same result, sorry it should be **recorder** configured?
 **_async def load_state_from_recorder (self):_**

**Comment by hhaim** [comment] 2020-08-03 06:43
1) try to remove the template 
2) Try to add logs here:

https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L198
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L205
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L247
https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L252

**Comment by Igor-kr** [comment] 2020-08-03 15:04
> 
> 
>     1. try to remove the template
> 
>     2. Try to add logs here:
> 
After adding the logger

> https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L198

2020-08-03 20:39:20 ERROR (MainThread) [custom_components.tasmota.sensor] 198 string (1) somthing is wrong new:(348) - old:(348) 

2020-08-03 20:42:20 ERROR (MainThread) [custom_components.tasmota.sensor] 198 string (1) somthing is wrong new:(349) - old:(349) 

After adding second logger
> https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L205

I found this :
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 229, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not subscriptable
2020-08-03 20:53:20 ERROR (MainThread) [homeassistant.util.logging] Exception in tele_received when handling msg on 'tele/tasmota_4B0C0B/SENSOR': '{"Time":"2020-08-03T20:53:19","COUNTER":{"C1":0,"C2":350,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.0},"TempUnit":"C"}'
Traceback (most recent call last):
  File "/config/custom_components/tasmota/sensor.py", line 141, in tele_received
    self.update_mqtt_sensor(payload)
  File "/config/custom_components/tasmota/sensor.py", line 161, in update_mqtt_sensor
    self.update_counter(new_counter)
  File "/config/custom_components/tasmota/sensor.py", line 209, in update_counter
    _LOGGER.error("205 line set new value (%d) somthing is wrong new:(%d) - old:(%d) ", diff,new_counter ,self._old_value)
UnboundLocalError: local variable 'diff' referenced before assignment



> https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L247
> https://github.com/hhaim/hass/blob/master/custom_components/tasmota/sensor.py#L252

**Comment by Igor-kr** [comment] 2020-08-03 15:40
After reboot:
2020-08-03 21:29:24 ERROR (MainThread) [custom_components.tasmota.sensor] 252 line- uptime_sec (63971) self._uptime_sec (100000000000) 
2020-08-03 21:29:24 ERROR (MainThread) [custom_components.tasmota.sensor] 205 line set new value  somthing is wrong new:(351) - old:(351) 

And this one after counter change:
2020-08-03 21:37:20 ERROR (MainThread) [custom_components.tasmota.sensor] 198 string (1) somthing is wrong new:(352) - old:(352)

**Comment by hhaim** [comment] 2020-08-03 15:49
Change this to 

LOGGER.error("205 line set new value (%d) somthing is wrong new:(%d) - old:(%d) ", 0,new_counter ,self._old_value)

Diff in not valid in 205

From your log everything looks good ..

Try to put a log in keepalive function that set the state to NONE

**Comment by hhaim** [comment] 2020-08-03 15:54
Set logs in 
174,176,185,212,215
And grab the logs for 10min (at least)

**Comment by Igor-kr** [comment] 2020-08-04 03:30
Hi, Here's what happened overnight. It looks like everything is fine! But why unavailable , I not understand!


[home-assistant(grep).log](https://github.com/hhaim/hass/files/5019943/home-assistant.grep.log)

**Comment by hhaim** [comment] 2020-08-04 05:09
It works fine, it just needs 3 readings to get the right value (uptime, oldvalue etc), you needed to wait.however see this 


```2020-08-04 03:43:22 ERROR (MainThread) [custom_components.tasmota.sensor] 252 line- uptime_sec (14) self._uptime_sec (86351) ```


Do you expect tasmota to reboot @ 03:43:22? in this case there is a need for another 3 reading to get the new diff. 
This is exactly what this component handles, but you should not have to reboot every few hours 


BTW I see that I've disabled  the keepalive (```_m_state``` and not ```_state```)  which should be fixed

**Comment by Igor-kr** [comment] 2020-08-04 06:00
I don't know why tasmota rebooted. There was no power outage.

**Comment by hhaim** [comment] 2020-08-04 11:10
@Igor-kr is it still  unavailable?

**Comment by Igor-kr** [comment] 2020-08-04 12:26
Yes

**Comment by hhaim** [comment] 2020-08-04 12:38
@Igor-kr  strange ...

```
 def update_uptime(self,uptime_sec):
            <<<<<<<<<<<<<<<  PUT log here (uptime_sec) and make sure it is **going up** and called every 1 minutes
        if uptime_sec < 0:

```

```
def update_uptime(self,uptime_sec):
        if uptime_sec < 0:
            return # nothing to update
        if uptime_sec < self._uptime_sec:
           # we had a reboot, need to take a new ref
           self._valid_ref = False 
           self._uptime_sec = uptime_sec
        else:
            self._uptime_sec = uptime_sec             <<<<<<<<<<<<<<<<<< it should reach to here every 1m after the first time to here ....
        self.async_schedule_update_ha_state()
```

**Comment by Igor-kr** [comment] 2020-08-05 11:26
Hi, sorry for delay I`m add this logger   


    def update_uptime(self,uptime_sec):
        _LOGGER.error("247 line check uptime_sec =  %d", uptime_sec)  <<<<<<<<<<
        if uptime_sec < 0: 
            _LOGGER.error("245 line uptime_sec (%d)", uptime_sec)
            return # nothing to update
        if uptime_sec < self._uptime_sec:
           # we had a reboot, need to take a new ref
           self._valid_ref = False 
           _LOGGER.error("252 line- uptime_sec (%d) self._uptime_sec (%d) ", uptime_sec, self._uptime_sec)
           self._uptime_sec = uptime_sec
        else:
            self._uptime_sec = uptime_sec
            _LOGGER.error("255 line check else : self._uptime_sec =  %d", self._uptime_sec)   <<<<<<<<
        self.async_schedule_update_ha_state()

[home-assistant(3).log](https://github.com/hhaim/hass/files/5027956/home-assistant.3.log)

**Comment by hhaim** [comment] 2020-08-05 12:20
@Igor-kr looks good, still does not understand why it does not work. last change 
Could you turn on the water to see that the counter is going up 

Can you add log before line 180 with the value  self._value   ,self._old_value , self._valid_ref  

```
   def update_counter(self,new_counter):
        LOG(new_counter,self._value   ,self._old_value , self._valid_ref)  <<<<<<<<<<
        if self._valid_ref:
            diff = 0  
            if new_counter < self._old_value:
                # check wrap of 64bit tasmota save it as 64bit 
               diff = (new_counter + 0xffffffff + 1) - self._old_value 
```

Another try maybe try to add (line 193) maybe something was changed in HASS
```
           if diff == 0: 
               self.update_state_value ()
               self.async_schedule_update_ha_state()
               return 
```

**Comment by hhaim** [comment] 2020-08-05 12:26
Another test to remove this lines 
```
        if self._expire_after is not None and self._expire_after > 0:
            async_track_time_interval(
                 self.hass, self._async_keepalive, timedelta(seconds=self._expire_after))

```

**Comment by Igor-kr** [comment] 2020-08-05 15:31
> 
> 
> @Igor-kr looks good, still does not understand why it does not work. last change
> Could you turn on the water to see that the counter is going up
> 
> Can you add log before line 180 with the value self._value ,self._old_value , self._valid_ref
> 
> ```
>    def update_counter(self,new_counter):
>         LOG(new_counter,self._value   ,self._old_value , self._valid_ref)  <<<<<<<<<<
>         if self._valid_ref:
>             diff = 0  
>             if new_counter < self._old_value:
>                 # check wrap of 64bit tasmota save it as 64bit 
>                diff = (new_counter + 0xffffffff + 1) - self._old_value 
> ```
Water is on, and counter change 
[home-assistant(Counter_water_on).log](https://github.com/hhaim/hass/files/5029353/home-assistant.Counter_water_on.log)

**Comment by Igor-kr** [comment] 2020-08-05 15:48
> 
> Another try maybe try to add (line 193) maybe something was changed in HASS
> 
> ```
>            if diff == 0: 
>                self.update_state_value ()
>                self.async_schedule_update_ha_state()
>                return 
> ```

Done, the same result!

Maybe something is wrong in the my config?

It under sensor: section

  - platform: tasmota
    name: hot_water_total
    stopic: tasmota_4B0C0B
    id: 2
    max_valid_diff: 2000
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (505360 + (value*10))|int }}"

**Comment by Igor-kr** [comment] 2020-08-05 15:59
> 
> 
> Another test to remove this lines
> 
> ```
>         if self._expire_after is not None and self._expire_after > 0:
>             async_track_time_interval(
>                  self.hass, self._async_keepalive, timedelta(seconds=self._expire_after))
> ```

Also without result

**Comment by hhaim** [comment] 2020-08-05 16:41
The logs are perfect, your configuration is perfect. 
The state is OK with the right value. The recorder is reading the right value from the database. 

```
2020-08-05 21:15:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.currentcost_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 229, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not subscriptable

```

Try to remove things from your configuration file and keep only this

```
platform: tasmota
name: hot_water_total
s topic: tasmota_4B0C0B
id: 2
max_valid_diff: 2000
unit_of_measurement: 'l'
icon: mdi:water-pump
expire_after: 300
value_template: "{{ (505360 + (value*10))|int }}"
```


The issue is not related to the component, it is something else

**Comment by hhaim** [comment] 2020-08-05 17:07
Another thing to test 
```
    expire_after: 0
```

**Comment by hhaim** [comment] 2020-08-05 17:08
For me it works fine with the same version (latest) with the same Python (3.8)
same configuration

**Comment by Igor-kr** [comment] 2020-08-05 17:22
In tasmota folder new folder __pycache__ found delete?

[__pycache__.zip](https://github.com/hhaim/hass/files/5030100/__pycache__.zip)

**Comment by hhaim** [comment] 2020-08-05 17:43
You can delete it. It will be created again

**Comment by Igor-kr** [comment] 2020-08-06 06:51
Good morning, I installed a new system from scratch and unfortunately the same result ! 

My configuration file

[configuration(2).yaml.zip](https://github.com/hhaim/hass/files/5033044/configuration.2.yaml.zip)

My log

[home-assistant(1).log](https://github.com/hhaim/hass/files/5033057/home-assistant.1.log)

Only one sensor includid

![IMG_3033](https://user-images.githubusercontent.com/68376689/89500268-45fd5600-d7e3-11ea-995c-0a9f02546042.jpg)
![IMG_3032](https://user-images.githubusercontent.com/68376689/89500279-4990dd00-d7e3-11ea-977e-5ffcc53e54d0.jpg)

**Comment by hhaim** [comment] 2020-08-06 07:49
I didn't test the obvious. Could you verify that you have it in Tasmota 

```tele/water_out/LWT = Online```

```
08:38:23 MQT: Connected
08:38:23 MQT: tele/water_out/LWT = Online (retained)
08:38:23 MQT: cmnd/water_out/POWER = 
```

**Comment by Igor-kr** [comment] 2020-08-06 08:39
**From Listen to a topic**


Message 2 received on tele/tasmota_4B0C0B/SENSOR at 2:24 PM:

{
    "Time": "2020-08-06T14:24:28",
    "COUNTER": {
        "C1": 0,
        "C2": 424,
        "C3": 53
    },
    "ANALOG": {
        "A0": 4
    },
    "DS18B20": {
        "Id": "021618547BEE",
        "Temperature": 34.1
    },
    "TempUnit": "C"
}

QoS: 0 - Retain: false
Message 1 received on tele/tasmota_4B0C0B/STATE at 2:24 PM:

{
    "Time": "2020-08-06T14:24:28",
    "Uptime": "0T10:41:20",
    "UptimeSec": 38480,
    "Heap": 25,
    "SleepMode": "Dynamic",
    "Sleep": 250,
    "LoadAvg": 16,
    "MqttCount": 2,
    "Wifi": {
        "AP": 1,
        "SSId": "Igor",
        "BSSId": "D0:54:2D:01:24:70",
        "Channel": 1,
        "RSSI": 74,
        "Signal": -63,
        "LinkCount": 1,
        "Downtime": "0T00:00:06"
    }
}

QoS: 0 - Retain: false
Message 0 received on tele/tasmota_4B0C0B/LWT at 2:23 PM:

Он-лайн

QoS: 0 - Retain: true

**From console of Tasmota**

14:29:29 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:29:29","Uptime":"0T10:46:21","UptimeSec":38781,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":17,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:29:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:29:29","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:30:28 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:30:28","Uptime":"0T10:47:20","UptimeSec":38840,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":15,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:30:28 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:30:28","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:31:29 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:31:29","Uptime":"0T10:48:21","UptimeSec":38901,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":17,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:31:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:31:29","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:32:29 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:32:29","Uptime":"0T10:49:21","UptimeSec":38961,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":17,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:32:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:32:29","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:33:28 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:33:28","Uptime":"0T10:50:20","UptimeSec":39020,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":22,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:33:28 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:33:28","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:34:28 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:34:28","Uptime":"0T10:51:20","UptimeSec":39080,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":17,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:34:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:34:28","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}
14:35:29 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:35:29","Uptime":"0T10:52:21","UptimeSec":39141,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":16,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:35:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:35:29","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":11},"DS18B20":{"Id":"021618547BEE","Temperature":34.2},"TempUnit":"C"}
14:36:28 MQT: tele/tasmota_4B0C0B/STATE = {"Time":"2020-08-06T14:36:28","Uptime":"0T10:53:20","UptimeSec":39200,"Heap":25,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":17,"MqttCount":2,"Wifi":{"AP":1,"SSId":"Igor","BSSId":"D0:54:2D:01:24:70","Channel":1,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:06"}}
14:36:29 MQT: tele/tasmota_4B0C0B/SENSOR = {"Time":"2020-08-06T14:36:28","COUNTER":{"C1":0,"C2":424,"C3":53},"ANALOG":{"A0":4},"DS18B20":{"Id":"021618547BEE","Temperature":34.1},"TempUnit":"C"}

**Comment by Igor-kr** [comment] 2020-08-06 08:49
**This is  probably**

Message 0 received on tele/tasmota_4B0C0B/LWT at 2:23 PM:

Он-лайн / Online

QoS: 0 - Retain: true

**Comment by hhaim** [comment] 2020-08-06 15:10
@Igor-kr I think I understand the issue. 

Your MQTT LWT message is not "Online"/"Offline" and because of that it is unavailable (this message is **retained** in the broker)

You have two options
1. Try to make your tasmota talk in English 
```
TASMOTA_ONLINE ="Online"
TASMOTA_OFFLINE = "Offline"
```
Get back to the original and try to remove the ```Он-лайн``` so it will be only English 

2.  Another option is to remove the ```MqttAvailability```  (there are 3 instances in this file)
```
class MqttTasmotaCounter(MqttAvailability,  RestoreEntity):
```

In this case you will not know that the device is going down (broker)

Sorry that I'm rusty, forgot about all of that

**Comment by Igor-kr** [comment] 2020-08-07 13:40
Ok! I downloaded the firmware in english and it worked! Thank you for your time!
Maybe mentions in the docs what works only with the english version of the tasmota firmware?

**Comment by hhaim** [comment] 2020-08-07 13:50
@Igor-kr suggest to raise question in Tasmota GitHub. It should be “Online” in all the languages

**Closed as completed** 2020-08-08 23:13 UTC
